### ISSUE TITLE
Login with Username and Password

### ISSUE THREAD

**Issue by yshah80** [yshah80/originate_pb_test_repo#3]
When loading the app
I want to enter my username and password
So that I can login and access my content

Rules:
- [ ] User should be prompted for their username and password (#6)
- [ ] Invalid credentials displays an error message (#7)
- [ ] Valid credentials logs the user in.

**Comment by yshah80** [comment]
Link to feature: https://originate-yash.productboard.com/feature-board/planning/features/733667
